version: "3.7"
services:
  mypostgres:
    image: postgres
    container_name: mypostgres
    ports:
      - "5435:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "ticketing-app"
    networks:
      - webnet
    volumes:
      - initdb:/var/lib/postgres/data
  ticketing-app:
    build: .
    container_name: ticketingapp
    ports:
      - "8080:8080"
    depends_on:
      - mypostgres
    networks:
      - webnet
volumes:
  initdb:
networks:
  webnet:
    driver: bridge


